
# small == 0, large == 1
itemnum_2_size_dict: {"1" :0,
#:"i_am_a_bunny_book",
"2" :0, #"laugh_out_loud_joke_book",
"3" :1, #"scotch_bubble_mailer",
"4" :0, #"up_glucose_bottle",
"5" :0, #"dasani_water_bottle",
"6" :0, #"rawlings_baseball",
"7" :1, #"folgers_classic_roast_coffee",
"8" :0, #"elmers_washable_no_run_school_glue",
"9" :1, #"hanes_tube_socks",
"10":0, #"womens_knit_gloves",
"11":0, # "cherokee_easy_tee_shirt",
"12":1, # "peva_shower_curtain_liner",
"13":0, # "cloud_b_plush_bear",
"14":0, # "barkely_hide_bones",
"15":0, # "kyjen_squeakin_eggs_plush_puppies",
"16":0, # "cool_shot_glue_sticks",
"17":1, # "creativity_chenille_stems",
"18":0, # "soft_white_lightbulb",
"19":0, # "safety_first_outlet_plugs",
"20":0, # "oral_b_toothbrush_red",
"21":1, # "dr_browns_bottle_brush",
"22":0, # "command_hooks",
"23":0, # "easter_turtle_sippy_cup",
"24":0, # "fiskars_scissors_red",
"25":0, # "scotch_duct_tape",
"26":0, # "woods_extension_cord",
"27":0, # "platinum_pets_dog_bowl",
"28":1, # "fitness_gear_3lb_dumbbell",
"29":1, # "rolodex_jumbo_pencil_cup",
"30":0, # "clorox_utility_brush",
"31":1, # "kleenex_paper_towels",
"32":0, # "expo_dry_erase_board_eraser",
"33":0, #"kleenex_tissue_box",
"34":0, # "ticonderoga_12_pencils",
"35":0, # "crayola_24_ct",
"36":0, # "jane_eyre_dvd",
"37":0, # "dove_beauty_bar",
"38":0 }# "staples_index_cards"}